add reference for psf_fwhm in LSST
aboucaud/galcheat pull request #82
Opened 2022-03-03 16:03 UTC by ismael-mendoza

2022-03-03 17:50 UTC, aboucaud commented
So it is not written plainly but I guess we can approximate it.

You read on section 2.1.5

> The total number of visits of any given area of sky, when accounting for all filters, should be of the order of 1,000

and

> The adopted time allocation (see Table 1) includes a slight preference to the r and i bands because of their dominant role in star/galaxy separation and weak lensing measurements.

On Table 1 you find the `mean number of visits`
| u | g | r | i | z | y |
| - | - | - | - | - | - |
| 56 | 80 | 184 | 184 | 160 | 160 | 

These account for 824 visits < 1,000 cited above. _Is this normal ?_

The first approximation that comes to mind would be to use that number directly and multiply it by the single exposure time : 15sec, or since they are done by pairs 30 sec.

Otherwise we use the table to compute the ratio between bands 
| u | g | r | i | z | y |
| - | - | - | - | - | - |
| 0.068 | 0.097 | 0.223 | 0.223 | 0.194 | 0.194 | 

and try to find the "mean_visit_full_exposure_time" that we can multiply these ratio with.

2022-03-04 06:36 UTC, mpaillassa commented
Hello @ismael-mendoza, thanks for looking into it. In fact I did not make the PR related to #25 yet so the LSST survey is not complete yet and misses references for:
* `pixel_size`, which may be the lone link between `zeropoint_airmass` and `zeropoint`, or the Table 1 in [the paper](https://arxiv.org/pdf/0805.2366v4.pdf) you mentioned.
* `sky_brightness`, which may be Table 2 in the [the paper](https://arxiv.org/pdf/0805.2366v4.pdf) as current (WLD) values are the same.
* `exposure_time`, which may be Table 1. As @aboucaud mentioned, we may approximate them using the number of visits. Considering visits of 30s, we can effectively find back the current (WLD) values.
* `psf_fwhm` before you started looking into it. I think it is ok now !

We may also use [the paper ](https://arxiv.org/pdf/0805.2366v4.pdf) you mention for the `obscuration` reference instead of citing WLD like currently done. From the 6.5m effective diameter given in the paper, `obscuration` is `1-(6.5*6.5)/(8.34*8.34)` giving 0.39257227.

2022-03-11 20:20 UTC, aboucaud commented
Just want to mention here the PR #97 in which I have completely changed the way references are written in the YAML files.

2022-03-17 09:32 UTC, aboucaud requested changes
PR #97 has been merged in main.
The changes should be adapted in consequence.

2022-03-17 21:06 UTC, ismael-mendoza commented
Thanks @aboucaud and @mpaillassa I'm looking into now and will take #97 into account.

2022-03-17 21:18 UTC, closed without merging

2022-03-17 21:24 UTC, ismael-mendoza commented
My bad, I accidentally closed this branch. I'm still learning the ropes of working from forks. Will open a new PR soon.